# Default

## Spring related configs

spring:

  ### Naming convention for database columns: CamelCase
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase.enabled: ${SPRING_LIQUIBASE_ENABLED}

  ### SGBDR MySQL properties
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_DOMAIN}/tir-sportif?useSSL=${SPRING_DATASOURCE_USE_SSL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

## Server configs

server:

  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: ${SERVER_SSL_KS}
    key-store-password: ${SERVER_SSL_PASSWORD}
    key-alias: ${SERVER_SSL_ALIAS}

security.require-ssl: true

## Custom app configs
tir-sportif:

  api:
    ### Default pages size
    pagination.size: 10

  jwt:
    secret: ${TIRSPORTIF_JWT_SECRET}
    validity: ${TIRSPORTIF_JWT_VALIDITY}

---

# Local

## Spring related configs

spring:

  profiles: local

  liquibase.enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/tir-sportif?useSSL=false
    username: admin
    password: password

  redis:
    host: localhost
    port: 6379
    password:

## Server configs

server:
  ssl:
    key-store: classpath:ssl/tir-sportif-local.p12
    key-store-password: password
    key-alias: local

## Custom app configs
tir-sportif:

  jwt:
    secret: springfield1911EMP
    validity: 3600000