# Default

## Spring related configs

spring:

  jpa:
    ### Naming convention for database columns: CamelCase
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ### Anti pattern, even logged by SpringBoot. See: https://stackoverflow.com/a/48222934/4675568
    open-in-view: false

  liquibase.enabled: ${SPRING_LIQUIBASE_ENABLED}

  ### SGBDR MySQL properties
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_DOMAIN}/tir-sportif?useSSL=${SPRING_DATASOURCE_USE_SSL}&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    time-unit: ${REDIS_TTL_TIMEUNIT}

## Custom app configs
tir-sportif:

  api:
    ### Default pages size
    pagination-size: 10

  jwt:
    secret: ${TIRSPORTIF_JWT_SECRET}
    validity: ${TIRSPORTIF_JWT_VALIDITY}

---

# Local

## Spring related configs

spring:

  profiles: local

  liquibase.enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/tir-sportif?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: password

  redis:
    host: localhost
    port: 6379
    password: password
    time-unit: MILLISECONDS

server.port: 8080

## Custom app configs
tir-sportif:

  jwt:
    secret: springfield1911EMP
    validity: 36000000 # 60min
