# Default

## Current app properties

### Server configs

server:
  port: 8081

### Spring related configs
spring:

  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  liquibase.enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/tir-sportif?useSSL=false
    username: admin
    password: password
    driver-class-name: com.mysql.jdbc.Driver

### Custom app configs
tir-sportif:

  jwt:
    secret: springfield1911EMP
    validity: 3600