# Default

## Current app properties

### Server configs

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:ssl/tir-sportif-local.p12
    key-store-password: password
    key-alias: local

security.require-ssl: true

### Spring related configs
spring:

  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  liquibase.enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/tir-sportif?useSSL=false
    username: admin
    password: password
    driver-class-name: com.mysql.jdbc.Driver

### Custom app configs
tir-sportif:

  jwt:
    secret: springfield1911EMP
    validity: 3600