# Default

## Server

server.port: ${PORT}

## Spring related configs

spring:

  jpa:
    ### Naming convention for database columns: CamelCase
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ### Anti pattern, even logged by SpringBoot. See: https://stackoverflow.com/a/48222934/4675568
    open-in-view: false
    show-sql: false

  liquibase.enabled: ${SPRING_LIQUIBASE_ENABLED}

  ### SGBDR MySQL properties
  datasource:
    url: ${SPRING_DATASOURCE_DOMAIN}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    time-unit: ${REDIS_TTL_TIMEUNIT}

## Custom app configs
tir-sportif:

  my-club:
    id: 1

  api:
    ### Default pages size
    pagination-size: 10

  jwt:
    secret: ${TIRSPORTIF_JWT_SECRET}
    validity: ${TIRSPORTIF_JWT_VALIDITY}

---

# Local

server.port: 8080

## Spring related configs

spring:

  profiles: local

  liquibase.enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/tir-sportif?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Paris&useLegacyDatetimeCode=false
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: password
    time-unit: MILLISECONDS

## Custom app configs
tir-sportif:

  my-club:
    id: 1

  jwt:
    secret: springfield1911EMP
    validity: 36000000 # 60min
