version: "3"
services:

  mysql:
    build: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ..
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - m2cache:/root/.m2/repository

networks:
  default:
    driver: bridge

volumes:
  m2cache:
  mysql:
