version: "3"
services:

  mysql:
    container_name: tir-sportif-mysql
    build: mysql
    env_file: ${ENV_FILE}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - tir-sportif_mysql:/var/lib/mysql

  postgres:
    container_name: tir-sportif-postgres
    build: postgres
    env_file: ${ENV_FILE}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - tir-sportif_postgres:/var/lib/postgresql/data

  redis:
    container_name: tir-sportif-redis
    build: ./redis
    env_file: ${ENV_FILE}
    ports:
      - "6379:6379"

  backend:
    container_name: tir-sportif-backend
    depends_on:
      - redis
      - mysql
    build:
      context: ..
      dockerfile: ../Dockerfile
    env_file: ${ENV_FILE}
    ports:
      - "8443:8443"
    volumes:
      - tir-sportif_m2cache:/root/.m2/repository

networks:
  default:
    driver: bridge

volumes:
  tir-sportif_m2cache:
  tir-sportif_mysql:
  tir-sportif_postgres:
